### ISSUE TITLE
[Mania] Note overlap and not using long notes

### ISSUE THREAD

**Issue by MasterZitron** [mappingtools/Mapperator#1]
### Two problems I found while using this tool was some notes overlapping with eachother

![image](https://user-images.githubusercontent.com/32692021/195955962-1119c341-5d7d-429a-bab0-fc48b2b77f93.png)

### And the lack of long notes

Visual representation of inverse ln maps after using the tool on it: 
![image](https://user-images.githubusercontent.com/32692021/195956461-b8a1e988-d3ad-4209-8e66-805059ff9b56.png)

**Comment by OliBomby** [comment]
Mapperator was never meant to work on mania. It would take a significant overhaul to make it work correctly on mania maps.
