### ISSUE TITLE
Add flag/parameter for iterative conversions

### ISSUE THREAD

**Issue by c-sig** [mappingtools/Mapperator#3]
Basically, a flag that continuously runs output through reconstruction up to a defined integer

`convert --data Data --input Input --output Output --repeat 10` would output Output10.osu wherein output would replace input 9 times after the first conversion

^ it would have the same function as
```
convert --data Data --input Input --output Output1
convert --data Data --input Output1 --output Output2
convert --data Data --input Output2 --output Output3
convert --data Data --input Output3 --output Output4
convert --data Data --input Output4 --output Output5
convert --data Data --input Output5 --output Output6
convert --data Data --input Output6 --output Output7
convert --data Data --input Output7 --output Output8
convert --data Data --input Output8 --output Output9
convert --data Data --input Output9 --output Output10
```

**Comment by OliBomby** [comment]
Does recursively running Mapperator improve the output or something? I'm curious about why you want to do this.

**Comment by c-sig** [comment]
in my specific use-case it kinda did?
started off with a strictly rhythm+ds template (int) and just ran it through mapperator a bunch of times, with varying results. im not really sure if i got lucky with these results or something but it definitely did a thing

[Mapperator.zip](https://github.com/mappingtools/Mapperator/files/9796062/Mapperator.zip)

**Comment by OliBomby** [comment]
It looks like the spacing steadily became lower as the iterations went up which is somewhat to be expected. I don't think the quality necessarily improved. I won't add recursive iterations because I have better things planned to actually improve the quality of results in Mapperator.
