### ISSUE TITLE
A little help?

### ISSUE THREAD

**Issue by SnoweeSzn** [mappingtools/Mapperator#5]
So, I was trying my hand at seeing if I could work the program and figured out how to use it but I ran into a slight issue.

Whenever I tried to convert a map, or extra beatmap/author data it just... didn't work? 

Whenever I started to convert a map it would work fine-ish, giving me this response after i pressed enter: https://gyazo.com/50451530ca0b8cbea2bf21fc5f8d022e

but then after it finished, it gave me this: https://gyazo.com/bdb1afd438cbcfb9c3858528b8c6e86e

but then after that I cant seem to figure out how to work the rest? I tried moving files around, copying .osu files into different folders, originally i had tried doing it by going straight to the .osu file in my songs folder but it kept giving me this error: 

https://gyazo.com/5d9c79c7e02a2ef1bb70e1fa09a71352 

not sure if its the spaces? or something else? I'm just really confused and would like some help.

**Comment by OliBomby** [comment]
the problem in the last screenshot is that the path to your input beatmap contains spaces and spaces are used to separate arguments so that doesnt work. You have to put quotes "" around the path to tell it that the path is one string. In the other screenshots the program worked correctly and created the output beatmap at `d:\mapperator\converted_beatmap.osu`

**Comment by OliBomby** [comment]
the beatmap should be created in the folder in which your Mapperator.ConsoleApp.exe is located.

**Comment by SnoweeSzn** [comment]
Yea I figured as much, just never showed up whenever I checked any of the locations, here's a video of me doing it in real time instead of just screenshots 

https://gfycat.com/CoarseLawfulBernesemountaindog

I'll keep trying and see if maybe something's going wrong but just not showing up?

**Comment by OliBomby** [comment]
I did a test and it seems like I was wrong. The path to the output file is actually relative to the location of the terminal, which in the video is `C:\WINDOWS\system32`. So the location of your output should be `C:\WINDOWS\system32\Ai_map.osu`.

**Comment by SnoweeSzn** [comment]
Yup I found it, thanks for the help this was all pretty confusing.
